[package]
name = "oath-adapter-net-http-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
oath-adapter-net-api = { workspace = true }
async-lock = { workspace = true }
thiserror = { workspace = true }
http = { workspace = true }
bytes = { workspace = true }
futures-util = { workspace = true }
http-body = { workspace = true }
http-body-util = { workspace = true }
pin-project-lite = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }
oath-adapter-net-mock = { workspace = true }
tracing-subscriber = { workspace = true }

[lints]
workspace = true
